# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [6]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
print(np.show_config())

1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CB

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
e = np.zeros(10)
print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [11]:
print(np.byte)
print(np.dtype)

<class 'numpy.int8'>
<class 'numpy.dtype'>


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
#python -c "import numpy as np; help(np.add)"
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [44]:
n = np.zeros(10)
n[4] =1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
f = np.array([1,2,3,4,5])
print(np.flip(f))

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
n =np.array([1,2,0,0,4,0])
print(np.nonzero(n))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
i = np.identity((3))
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
n = np.random.random((3,3,3))
print(n)

[[[0.57415964 0.91117381 0.03251902]
  [0.00342772 0.86354621 0.758104  ]
  [0.42039648 0.57779596 0.08766059]]

 [[0.04183675 0.38159265 0.96263854]
  [0.62752102 0.79637333 0.03695913]
  [0.62005749 0.04892379 0.06094556]]

 [[0.22256111 0.22745052 0.27226806]
  [0.75736855 0.70634727 0.56716842]
  [0.28756989 0.08267565 0.32092625]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
a = np.random.rand(10,10)
print(a)
print('\r')
print(a.min())
print('\r')
print(a.max())

[[0.52337793 0.15619896 0.28499898 0.39926866 0.03723964 0.26929434
  0.81608926 0.18934943 0.02847655 0.73781583]
 [0.23402214 0.47349489 0.47307542 0.43686865 0.70153963 0.53795978
  0.46226448 0.14272715 0.94385363 0.90843221]
 [0.89470149 0.5599971  0.52194754 0.27654602 0.22127938 0.7051242
  0.10350992 0.57100933 0.12642485 0.41661283]
 [0.46929521 0.71959453 0.43121781 0.00479113 0.059785   0.81358539
  0.50146902 0.42626992 0.1564791  0.86695886]
 [0.7342938  0.25283509 0.55986181 0.13966147 0.68462019 0.93800858
  0.30766031 0.63949025 0.51418279 0.95290874]
 [0.81544116 0.74524416 0.63145312 0.7634851  0.4303967  0.59497686
  0.86472099 0.18238019 0.82659644 0.45284959]
 [0.30685435 0.14296907 0.25812879 0.53151148 0.7751485  0.36049995
  0.01263311 0.80305799 0.59706126 0.96065011]
 [0.83376283 0.8198429  0.40062182 0.06040306 0.40200858 0.91582492
  0.46820877 0.01704023 0.37290627 0.79238321]
 [0.71710003 0.42507519 0.98241164 0.66283785 0.82546425 0.16020095
  0.16803489 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
v = np.random.rand(30)
print(v)
print('\r')
print(v.size)
print('\r')
print(np.mean(v))

[0.08839801 0.51372165 0.07098921 0.90437197 0.72834126 0.81543464
 0.12229652 0.74015716 0.38340468 0.00257099 0.39156008 0.0743946
 0.78670448 0.04511245 0.34627474 0.67805819 0.44946351 0.3839491
 0.72410592 0.89475841 0.60763004 0.95583297 0.22581257 0.57215011
 0.47530113 0.12109596 0.20174235 0.99950201 0.7545908  0.62245361]

30

0.48933930368416223


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
import numpy as np
r = np.ones((5,5))
r[1:-1,1:-1] = 0
r

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [36]:
b = np.zeros((5,5))
b[1:-1,1:-1] = 1
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
existing_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
row,cols = existing_array.shape
new_arr = np.zeros((row+2,cols+2),dtype=existing_array.dtype)
new_arr[1:-1,1:-1] = existing_array
print(existing_array)
print('\r')
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [173]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print('\r')
print(0.3 == 3 * 0.1)

nan
False
False
nan
True

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [57]:
import numpy as np
print(np.diag([1,2,3,4],k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [59]:
import numpy as np
matrix = np.zeros((8,8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [61]:
shape = (6,7,8)
f = 100
indices = np.unravel_index(f,shape)
print(indices)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [70]:
checkerboard = np.array([[0,1],[1,0]])
checkerboard_ = np.tile(checkerboard,(4,4))
checkerboard_

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [78]:
import numpy as np
n = np.random.random((5,5))
normalize = (n-np.min(n))/(np.max(n)-np.min(n))
print(n)
print('\r')
print(normalize)

[[0.5746463  0.44409738 0.89557596 0.68233974 0.89650628]
 [0.4256656  0.97087624 0.07227672 0.13709362 0.21446238]
 [0.48319542 0.92188177 0.67850284 0.82061901 0.51310739]
 [0.4449925  0.28171626 0.24056343 0.8939068  0.64289173]
 [0.46412228 0.87763742 0.91776607 0.73902128 0.07128367]]

[[0.55954511 0.41442506 0.91629514 0.67925869 0.91732929]
 [0.39393603 1.         0.00110388 0.07315529 0.15915951]
 [0.45788701 0.94553705 0.67499354 0.83297191 0.49113758]
 [0.41542009 0.23391988 0.18817381 0.91443967 0.63540771]
 [0.43668503 0.89635439 0.94096198 0.7422667  0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [84]:
import numpy as np
color_dtype = np.dtype([('R',np.uint8),('G',np.uint8),('B',np.uint8),('A',np.uint8)])
color_array =np.array([(255,0,0,255),
                (0,255,0,128),
                (0,0,255,255)],
              dtype=color_dtype)
print(color_array)

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [91]:
m1 = np.arange(15).reshape(5,3)
m2 = np.arange(6).reshape(3,2)
multiply = np.dot(m1,m2)
print(multiply)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [96]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[(arr>=3) & (arr<=8)] *=-1
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [102]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [111]:
z = 5
print(z**z)
print(2<<z<<2)
print(z<-z)
print(1j*z)
print(z/1/1)
print(z<z>z)

3125
256
False
5j
5.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [115]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_19784\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_19784\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [118]:
a = np.array([1.2,3.4,0.6])
round_away = np.ceil(a)
round_away

array([2., 4., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [122]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
common_value = np.intersect1d(a,b)
common_value

array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [51]:
import numpy as np
np.seterr(all='ignore')
np.seterr

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [124]:
import numpy as np
np.seterr(all = 'warn')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [127]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


C:\Users\Administrator\AppData\Local\Temp\ipykernel_19784\1251884223.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_19784\1251884223.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [131]:
import numpy as np
from datetime import datetime, timedelta
today = np.datetime64(datetime.now())
yesterday = today - np.timedelta64(1,'D')
tomarrow = today + np.timedelta64(1, 'D')
t_d = today.astype(datetime)
y_d = yesterday.astype(datetime)
t_m = tomarrow.astype(tomarrow)
print(t_d)
print(y_d)
print(t_m)

2023-12-19 14:07:51.538007
2023-12-18 14:07:51.538007
2023-12-20T14:07:51.538007


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [136]:
from calendar import month
yy = 2016
mm = 7
print(calendar.month(dd,mm))

       July 7
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [231]:
import numpy as np

A = np.array([1, 2, 3],dtype=np.float64)
B = np.array([4, 5, 6],dtype = np.float64)

# Compute ((A + B) * (-A / 2)) in place
A += B
A *= -A / 2

# Print the result
print("Result:", A)


Result: [-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [153]:
r = np.random.rand(5)*10
print(np.floor(r).astype(int))
print(np.ceil(r).astype(int))
print(r.astype(int))
print(np.trunc(r).astype(int))

[1 5 6 9 7]
[ 2  6  7 10  8]
[1 5 6 9 7]
[1 5 6 9 7]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [187]:
n = np.arange(5)
np.tile(n,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [163]:
a  = np.arange(2)
a1 = np.tile(a,(5,5))
a1

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [169]:
import numpy as np
vector = np.linspace(0, 1, num=12)[1:-1]
print("Vector:", vector)

Vector: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [172]:
r = np.random.rand(10)
print(r)
print(r.sort())
r

[0.55053625 0.48072005 0.5651977  0.35873297 0.66585602 0.75790949
 0.25196646 0.82533304 0.12274827 0.59217268]
None


array([0.12274827, 0.25196646, 0.35873297, 0.48072005, 0.55053625,
       0.5651977 , 0.59217268, 0.66585602, 0.75790949, 0.82533304])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [193]:
A = np.array([1,2,3,4])
B = np.array([1,2,3,4])
np.array_equal(A,B)

True

In [194]:
a = np.random.rand(5,5)
b = np.random.rand(5,5)
np.array_equal(a,a)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [195]:
arr = np.array([1,2,3,4])
tup = tuple(arr)
print(tup)

(1, 2, 3, 4)


In [199]:
arr = np.array([5,6,7,8,9])
arr.flags.writeable = False
arr

array([5, 6, 7, 8, 9])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [219]:
r = np.random.rand(10)
m = np.argmax(r)
print(m)
r[m] = 0
r

4


array([0.19163145, 0.09354542, 0.82307992, 0.64344595, 0.        ,
       0.20235522, 0.02400939, 0.82446744, 0.38694442, 0.35829134])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [221]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[:])
arr

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [226]:
a = np.array([1.2,3.4,5.6],dtype=np.float32)
a1 = a.view(dtype=np.int32)
print(a1.dtype)
print(a1)

int32
[1067030938 1079613850 1085485875]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)