# Image to Array

In [1]:
import numpy as np
import cv2 as cv

In [2]:
img = cv.imread("man.jpg",0)
print(img)

[[ 68  70  73 ...  85  86  86]
 [ 68  70  73 ...  89  89  89]
 [ 69  71  74 ...  92  92  93]
 ...
 [ 53  39  27 ... 153 152 152]
 [ 51  46  37 ... 153 152 152]
 [ 47  52  45 ... 153 152 152]]


In [3]:
print(img.shape)

(500, 500)


In [4]:
img2 = cv.imread("square.jpg",0)
print(img2)

[[255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]


# Image Reading

In [5]:
img3 = cv.imread("man.jpg")
cv.imshow("person",img2)
cv.waitKey(0)
cv.destroyAllWindows()

# 3. Image Writing/Saving


In [6]:
cv.imwrite("person.jpg",img3)

True

# 4. Image Resizing

In [7]:
import cv2 as cv
img4 = cv.imread('ghayur.jpg')
img5 = cv.resize(img4,(256,256))
cv.imshow("pic",img4)
cv.imshow("res_pic",img5)
cv.waitKey()
cv.destroyAllWindows()

# 5. Converting Color Image to Grayscal

In [8]:
import cv2 as cv
img6 = cv.imread('ghayur.jpg')
gray = cv.cvtColor(img6,cv.COLOR_BGR2GRAY)
cv.imshow("origional",img6)
cv.imshow("pic",gray)
cv.waitKey(0)
cv.destroyAllWindows()

# 6. Image Blurring

In [9]:
img7 = cv.imread('lady.jpg')
blur = cv.GaussianBlur(img7, (35,35),0)
cv.imshow("blur",blur)
cv.waitKey(0)
cv.destroyAllWindows()

# 7. Image Flipping


In [10]:
img7 = cv.imread('lady.jpg')
flip = cv.flip(img7,-1)
cv.imshow("blur",flip)
cv.waitKey(0)
cv.destroyAllWindows()

# 8. Drawing on Image (Rectangle)

In [11]:
img9 = np.zeros((512,512,3))

# Rectangle (image, start_point, end_point, color, thickness)
# I have chosen a red color for my rectangle with a thickness of 10

img9 = cv.rectangle(img9, (200,200), (300,300), (0,0,255), 10)
cv.imshow("Rectangle", img9)
cv.waitKey(0)
cv.destroyAllWindows()

# 9. Drawing on Image (Text)

In [12]:
import cv2 as cv
import numpy as np
img10 = np.zeros((512,512,3))

In [13]:
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img10, 'computer vision',(125,250), font,1,(0,0,255),2)
cv.imshow('text', img10)
cv.waitKey(0)
cv.destroyAllWindows()

# 11. Image Edge Detection


In [14]:
img13 = cv.imread('lady.jpg')
edge = cv.Canny(img13, 100,200)
cv.imshow('image',edge)
cv.waitKey(0)
cv.destroyAllWindows()