# Basic Python

In [3]:
for i in range(1,4):
    for j in range(1,4):
        print(i,j)

1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3


In [9]:
fruit = ['apple','banana','orange']
color = ['red','yellow','red']
for fruit,color in zip(fruit,color):
    print(fruit,'is',color)


apple is red
banana is yellow
orange is red


In [2]:
name = ['ghayur','qayyume','hubdar']
age = [20,14,8]
for n,a in zip(name,age):
    print(n,a)

ghayur 20
qayyume 14
hubdar 8


In [4]:
name = ['ghayur','qayyume','hubdar']
age = [20,14,8]
for n in name:
    for a in age:
        print(n,a)

ghayur 20
ghayur 14
ghayur 8
qayyume 20
qayyume 14
qayyume 8
hubdar 20
hubdar 14
hubdar 8


In [1]:
name = 'ghayur abbas'
name2 = 'qayyum khan'
s1 = name.split()
s2 = name2.split()
for a,b in zip(s1,s2):
    print(a,b)

ghayur qayyum
abbas khan


In [5]:
t = ((1,2),(3,4),(5,6))
for a in t:
    print(a)

(1, 2)
(3, 4)
(5, 6)


In [22]:
t = ((1,2),(3,4),(5,6))
for a in t:
    for b in a:
        print(a,b)

(1, 2) 1
(1, 2) 2
(3, 4) 3
(3, 4) 4
(5, 6) 5
(5, 6) 6


In [23]:
for a in t:
    for b in a:
        print(b)

1
2
3
4
5
6


In [50]:
l = 'geeksforgeeks'
for i in l:
    if i == 'e' or i =='s':
        continue
    print(i)

g
k
f
o
r
g
k


In [58]:
l = 'geeksforgeeks'
for i in l:
    if i == 'e' or i == 's':
        break
    print(letter)

e


In [59]:
l = 'geeksforgeeks'
for s in l:
    pass
print(s)

s


In [75]:
for letter in 'geeksforgek':
    if letter == 'o':
        pass
print('Last Letter :', letter)

Last Letter : k


In [9]:
sum = 0
for i in range(1,10):
    sum = sum+i
sum

45

In [11]:
for i in range(1,4):
    print(i)
else:
    print('break')

1
2
3
break


In [7]:
i = 0
while i<=5:
    print(i*'*')
    i+=1


*
**
***
****
*****


In [1]:
i = 5
while i>=0:
    print(i*'*')
    i-=1

*****
****
***
**
*



In [3]:
count = 0
while count<5:
    count = count+1
    print(count)
    count +=1


1
3
5


In [6]:
count = 0
while count<3:
    count = count+1
    print('ghayur Abbas')


ghayur Abbas
ghayur Abbas
ghayur Abbas


In [9]:
a = [1,2,3,4,5]
while a:
    print(a.pop())

5
4
3
2
1


In [17]:
count = 0
while count <5: count+=1; print('hi')

hi
hi
hi
hi
hi


In [18]:
a = 'geeksforgeeks'
for i in a:
    if i == 'e' or i=='s':
        continue
    print(i)

g
k
f
o
r
g
k


In [1]:
i = 0
a = 'geeksforgeeks'
while i < len(a):
    if a[i] == 'e' or a[i] == 's':
        i = i+1
        continue
    print(a[i])  
    i = i+1


g
k
f
o
r
g
k


In [2]:
a = 'geeksforgeeks'
i = 0
while i < len(a):
    if a[i] == 's' or a[i] == 'e':
        i = i+1
        break
    print(a[i])
    i = i+1
              

g


In [1]:
i = 0
a = 'geeksforgeeks'
while i <len(a):
    i+=1
    pass
print(i)

13


In [2]:
a = 'geeksforgeeks'
i = 0
while i < len(a):
    i += 1
    pass
 
print('Value of i :', i)

Value of i : 13


In [11]:
i = 0
while i < 4:
    i+=1
    print(i)
else:
    print('\nbreak')

1
2
3
4

break


In [12]:
i = 0
while i < 4:
    i+=1
    print(i)
    break
else:
    print('no break')
    

1


In [9]:
i = 0
while i < 4:
    i += 1
    print(i)
else: # Executed because no break in for
    print("No Break\n")


1
2
3
4
No Break



In [10]:
i = 0
while i < 4:
    i += 1
    print(i)
    break
else: # Not executed as there is a break
    print("No Break")


1


In [14]:
a = int(input('Enter a number (-1 to quit): '))
while a != -1:
    a = int(input('Enter a number (-1 to quit): '))

Enter a number (-1 to quit): 1
Enter a number (-1 to quit): 1
Enter a number (-1 to quit): -1


In [6]:
a = (int(input('enter a 1 to quit: ')))
while a != 1:
    a = (int(input('enter a 1 to quit: ')))


enter a 1 to quit: 2
enter a 1 to quit: 3
enter a 1 to quit: 1


In [11]:
for i in range(10):
    if i ==2:
        break
    print(i)

0
1


In [12]:
for i in range(10):
    print(i)
    if i == 2:
        break

0
1
2


In [17]:
num = 0
for i in range(10):
    num += 1
    if num == 8:
        break
    print("The num has value:", num)
print("Out of loop")


The num has value: 1
The num has value: 2
The num has value: 3
The num has value: 4
The num has value: 5
The num has value: 6
The num has value: 7
Out of loop


In [20]:
num = 0
for i in range(10):
    num = num+1
    if num == 8:
        break
    print("the num has value: ",num)
print('end of loop')

the num has value:  1
the num has value:  2
the num has value:  3
the num has value:  4
the num has value:  5
the num has value:  6
the num has value:  7
end of loop


In [21]:
for var in 'GEEKSFORGEEKS':
    if var == 'E':
        continue
    print(var)

G
K
S
F
O
R
G
K
S


In [23]:
for i in range(10):
    if i == 6:
        continue
    else:
        print(i)

0
1
2
3
4
5
7
8
9


In [24]:
# Bubble Sort

In [49]:
my_list = [64, 34, 25, 12, 22, 11, 90]
n = len(my_list)
for i in range(n):
    for j in range(0, n-i-1):
        if my_list[j] > my_list[j+1]:
            my_list[j], my_list[j+1] = my_list[j+1], my_list[j]
        print(my_list)

[34, 64, 25, 12, 22, 11, 90]
[34, 25, 64, 12, 22, 11, 90]
[34, 25, 12, 64, 22, 11, 90]
[34, 25, 12, 22, 64, 11, 90]
[34, 25, 12, 22, 11, 64, 90]
[34, 25, 12, 22, 11, 64, 90]
[25, 34, 12, 22, 11, 64, 90]
[25, 12, 34, 22, 11, 64, 90]
[25, 12, 22, 34, 11, 64, 90]
[25, 12, 22, 11, 34, 64, 90]
[25, 12, 22, 11, 34, 64, 90]
[12, 25, 22, 11, 34, 64, 90]
[12, 22, 25, 11, 34, 64, 90]
[12, 22, 11, 25, 34, 64, 90]
[12, 22, 11, 25, 34, 64, 90]
[12, 22, 11, 25, 34, 64, 90]
[12, 11, 22, 25, 34, 64, 90]
[12, 11, 22, 25, 34, 64, 90]
[11, 12, 22, 25, 34, 64, 90]
[11, 12, 22, 25, 34, 64, 90]
[11, 12, 22, 25, 34, 64, 90]


In [51]:
import numpy as np
my_list = np.array([64, 34, 25, 12, 22, 11, 90])
n = len(my_list)
for i in range(n):
    for j in range(0,n-i-1):
        if my_list[j] > my_list[j+1]:
            my_list[j],my_list[j+1] = my_list[j+1],my_list[j]
        print(my_list)

[34 64 25 12 22 11 90]
[34 25 64 12 22 11 90]
[34 25 12 64 22 11 90]
[34 25 12 22 64 11 90]
[34 25 12 22 11 64 90]
[34 25 12 22 11 64 90]
[25 34 12 22 11 64 90]
[25 12 34 22 11 64 90]
[25 12 22 34 11 64 90]
[25 12 22 11 34 64 90]
[25 12 22 11 34 64 90]
[12 25 22 11 34 64 90]
[12 22 25 11 34 64 90]
[12 22 11 25 34 64 90]
[12 22 11 25 34 64 90]
[12 22 11 25 34 64 90]
[12 11 22 25 34 64 90]
[12 11 22 25 34 64 90]
[11 12 22 25 34 64 90]
[11 12 22 25 34 64 90]
[11 12 22 25 34 64 90]


In [1]:
for i in range(1,11):
    if i==6:
        continue
    print(i)

1
2
3
4
5
7
8
9
10


In [2]:
nested_l = [[1,2,3],[4,5,6],[7,8,9]]
for i in nested_l:
    for j in i:
        if j == 3:
            continue
        print(j)

1
2
4
5
6
7
8
9


In [4]:
for i in range(0,10):
    if i == 5:
        continue
    print(i)

0
1
2
3
4
6
7
8
9


In [1]:
i = 0
while i < len(range(10)):
    if i == 5:
        i = i+1
        continue
    print(i)
    i+=1

0
1
2
3
4
6
7
8
9


In [2]:
i = 0
while i < 10:
    if i == 5:
        i += 1
        continue
    print(i)
    i += 1


0
1
2
3
4
6
7
8
9


In [5]:
for a,b in enumerate(['Big', 'Bang','theorey']):
    print(a,b)

0 Big
1 Bang
2 theorey


In [6]:
for key, value in enumerate(['The', 'Big', 'Bang', 'Theory']):
    print(key, value)


0 The
1 Big
2 Bang
3 Theory


In [16]:
for b in ['my','name','is','ghayur']:
    print(b,end = ' ')

my name is ghayur 

In [17]:
n = ['ghayur','qayyum','hubdar']
a = [20, 16,10]
for n,a in zip(n,a):
    print(n,a)

ghayur 20
qayyum 16
hubdar 10


In [22]:
question = ['name','color','shape']
answer = ['apple','red','a circle']
for a,b  in zip(question,answer):
    print(a,b)

name apple
color red
shape a circle


In [27]:
question = ['name','color','shape']
answer = ['apple','red','a circle']
for a,b  in zip(question,answer):
    print('what is your {0}, my {0} is {1}'.format(a,b))

what is your name, my name is apple
what is your color, my color is red
what is your shape, my shape is a circle


In [30]:
d = {'name':'ghayur', 'age':20, 'class':'bscs'}
for key,value in d.items():
    print(key,value)

name ghayur
age 20
class bscs


In [32]:
d = {'name':'ghayur', 'age':20, 'class':'bscs'}
for key in d.keys():
    print(key)

name
age
class


In [33]:
d = {'name':'ghayur', 'age':20, 'class':'bscs'}
for value in d.values():
    print(value)

ghayur
20
bscs


In [6]:
lis = [1, 3, 5, 6, 2, 1, 3]
l = (lis.sort())
print(l)
l

None


In [10]:
lis = [1, 3, 5, 6, 2, 1, 3]
for i in sorted(lis):
    print(i,end = ' ')

1 1 2 3 3 5 6 

In [8]:
lis = [1, 3, 5, 6, 2, 1, 3]
n = len(lis)
for i in range(n):
    for j in range(0,n-i-1):
        if lis[j] > lis[j+1]:
            lis[j],lis[j+1] = lis[j+1],lis[j]
        print(lis)

[1, 3, 5, 6, 2, 1, 3]
[1, 3, 5, 6, 2, 1, 3]
[1, 3, 5, 6, 2, 1, 3]
[1, 3, 5, 2, 6, 1, 3]
[1, 3, 5, 2, 1, 6, 3]
[1, 3, 5, 2, 1, 3, 6]
[1, 3, 5, 2, 1, 3, 6]
[1, 3, 5, 2, 1, 3, 6]
[1, 3, 2, 5, 1, 3, 6]
[1, 3, 2, 1, 5, 3, 6]
[1, 3, 2, 1, 3, 5, 6]
[1, 3, 2, 1, 3, 5, 6]
[1, 2, 3, 1, 3, 5, 6]
[1, 2, 1, 3, 3, 5, 6]
[1, 2, 1, 3, 3, 5, 6]
[1, 2, 1, 3, 3, 5, 6]
[1, 1, 2, 3, 3, 5, 6]
[1, 1, 2, 3, 3, 5, 6]
[1, 1, 2, 3, 3, 5, 6]
[1, 1, 2, 3, 3, 5, 6]
[1, 1, 2, 3, 3, 5, 6]


In [10]:
lis = [1, 3, 5, 6, 2, 1, 3]
for i in sorted(set(lis)):
    print(i,end=' ')

1 2 3 5 6 

In [18]:
lis = [1, 3, 5, 6, 2, 1, 3]
for j in reversed(lis):
    print(j,end = ' ')

3 1 2 6 5 3 1 

# how to find occurance of number

In [1]:
def check_acc(lst, tar):
    count =  0
    for i in lst:
        if i == tar:
            count = count+1
    return count
lst = [1,2,3,4,5,6,7,5,5,5,5]
tar = 5
check_acc(lst,tar)

5

In [2]:
a = [1,22,33,4,22,3,4,4,22,3]
count = 0
for i in a:
    if i == 22:
        count+=1
    else: 
        pass
print(count)

3


In [6]:
for i in reversed(range(1,10,4)):
    print(i)

9
5
1


In [1]:
count =  0
while count < 5:
    if count == 3:
        print('count is 3')
    count+=1

count is 3


In [3]:
def fun():
    print("welcomt to GFG")
fun()

welcomt to GFG


In [9]:
def add(num1:int,num2:int) -> int:
    """Add Two Numbe"""
    sum = num1+num2
    return sum
num1,num2 = 5,10
result = add(num1,num2)
print(f"the addition of {num1} and {num2} is {result}")

the addition of 5 and 10 is 15


In [12]:
def fun(x):
    if x%2== 0:
        print("Even")
    else:
        print("Odd")
fun(10)

Even


In [13]:
def fun(x,y = 10):
        print(x)
        print(y)
fun(15)

15
10


In [16]:
def student(f_name,l_name):
    print(f_name,l_name)
student(f_name = "ghayur",l_name="abbas")
student(l_name="abbas",f_name = "ghayur")

ghayur abbas
ghayur abbas


In [24]:
def evenodd(x):
    if (x%2 == 0):
        print("Even")
    else:
        print("odd")
evenodd(150)

Even


In [25]:
def df1():
    s = "i love pakistan"
    def df2():
        print(s)
    df2()
df1()

i love pakistan


In [26]:
def cube(x):
    return x*x*x
cube(5)

125

In [35]:
l2 = lambda x = 5: x*x*x
print(l2())

125


In [36]:
def seq(num):
    return num**2
seq(5)

25

In [38]:
def fun(x):
    x = [1,2,3,4]
    return x
y = [5,6,7,8]
fun(y)

[1, 2, 3, 4]

In [41]:
def swap(x,y):
    temp = x
    x = y
    y = temp
x = 5
y = 7
swap(x,y)
print(x)
print(y)

5
7


In [46]:
def swap(x, y):
 temp = x
 x = y
 y = temp
 return y
# Driver code
x = 2
y = 3
swap(x, y)
print(x)
print(y)


2
3


In [53]:
n_list = ["happy",[1,2,3,4]]
print(n_list[0][0])
print(n_list[1][3])
print(n_list[0][-5])

h
4
h


In [56]:
odd = [1,2,3,4]
odd[0:2] = [5,5]
odd

[5, 5, 3, 4]

In [60]:
odd.append(7)
print(odd)
print(odd.pop(3))

[5, 5, 3, 4, 7, 7, 7]
4


In [61]:
odd.extend([3,2,1])
print(odd)

[5, 5, 3, 7, 7, 7, 3, 2, 1]


In [65]:
print(odd.pop(7))

2


In [66]:
print(odd)

[5, 5, 3, 7, 7, 7, 3, 1]


In [68]:
print(str(odd) + "ghayur")

[5, 5, 3, 7, 7, 7, 3, 1]ghayur


In [70]:
odd = [1, 3, 5]
print(odd + [9, 7, 5])

[1, 3, 5, 9, 7, 5]


In [71]:
print(odd+[10,10])

[1, 3, 5, 10, 10]


In [72]:
print(odd)

[1, 3, 5]


In [75]:
print(["re"]*3)

['re', 're', 're']


In [79]:
even = [2,4,2]
even.insert(2,6)
print(even)

[2, 4, 6, 2]


In [80]:
even[4:4] = [8,10,12]

In [81]:
even

[2, 4, 6, 2, 8, 10, 12]

In [83]:
del even[2]
even

[2, 4, 8, 10, 12]

In [86]:
del even[4]
even

[2, 4, 8, 10]

In [87]:
del even

In [89]:
even

NameError: name 'even' is not defined

In [90]:
t = ()
t

()

In [93]:
t = (1,2,3.5,"ghayur")
t

(1, 2, 3.5, 'ghayur')

In [94]:
t = ("ghayur",[12,3,4],[5,6,7])
t

('ghayur', [12, 3, 4], [5, 6, 7])

In [95]:
a = 1,2,3,"ghayur"
a

(1, 2, 3, 'ghayur')

In [96]:
a,b,c,d = a

In [97]:
a

1

In [98]:
b

2

In [99]:
c

3

In [100]:
d

'ghayur'