# Numpy Basic

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
a1 = np.array(a)
print(a1)

[1 2 3 4 5]


In [3]:
a = np.array([5,4,32,2])
print(a)

[ 5  4 32  2]


In [5]:
a = [1,2,20,28]
a1 = np.array(a,np.int8)
print(a1)
print(a1.dtype)

[ 1  2 20 28]
int8


In [7]:
a = np.array([5,4,3222222,6],np.int8)
print(a)
print(a.dtype)

[  5   4 -50   6]
int8


In [12]:
a4 = np.array([1,2,3,4,5])
print(a4[4])


5


# ONE_D ARRAY

In [38]:
o_d =np.array([1,2,3,4,6],np.int32)
print(o_d)
print(o_d.dtype)
print(o_d.shape)
print(o_d.size)

[1 2 3 4 6]
int32
(5,)
5


# TWO_D ARRAY

In [48]:
two_d = np.array([[1,2,3],[4,5,6]],np.int64)
print(two_d)
print(two_d.dtype)
print(two_d.shape)
print(two_d.size)

[[1 2 3]
 [4 5 6]]
int64
(2, 3)
6


# THREE_D ARRAY

In [49]:
t_d = np.array([[[1,2],[3,4],[5,6]]])
print(t_d)
print(t_d.shape)
print(t_d.dtype)
print(t_d.size)

[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)
int32
6


In [50]:
a = np.array([[[[[[4,5]]]]]])
print(a)
print(a.shape)
print(a.size)
print(a.dtype)

[[[[[[4 5]]]]]]
(1, 1, 1, 1, 1, 2)
2
int32


In [47]:
r = [1,2,3,3,4,5]
r1 = np.array(r)
r1[3] = 10
print(r1)
print(r1.size)
print(r1.shape)
print(r1.dtype)

[ 1  2  3 10  4  5]
6
(6,)
int32


# INTRINSIC NUMPY

# Zeros

In [53]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
z1 = np.zeros((4,4))
print(z1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ARANGE

In [60]:
a = np.arange((3))
print(a)

[0 1 2]


# RESHAPE

In [64]:
r = np.array([3,4,5,6,7,4])
print(r.reshape(2,3))

[[3 4 5]
 [6 7 4]]


In [65]:
print(r.reshape(3,2))

[[3 4]
 [5 6]
 [7 4]]


# RAVEL

In [66]:
print(r.ravel())

[3 4 5 6 7 4]


In [68]:
r2 = np.array([1,2,3,4,5,6,7,8])
print(r2.reshape(2,4))
print(r2.ravel())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# LINSPACE

In [69]:
l = np.linspace(1,5,10)
print(l)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [71]:
l2 = np.linspace(2,12,5)
print(l2)

[ 2.   4.5  7.   9.5 12. ]


# EMPTY

In [73]:
import numpy as np
e = np.empty((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# IDENTITY

In [77]:
i = np.identity((3))
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ONES

In [81]:
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# AXIS

In [87]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.ndim)

[5 7 9]
[ 6 15]
2


In [88]:
a = np.array([[1,2,3],[7,8,9]],ndmin=10)
print(a)
print(a.ndim)


[[[[[[[[[[1 2 3]
         [7 8 9]]]]]]]]]]
10


In [117]:
a = np.array([[1,2,3],[4,5,6]])
print(a[1,1])
print(a[1][2])
print(a.dtype)
print(a.nbytes)
print(a.argmax())
print(a.argmin())
print(a.argsort())

5
6
int32
24
5
0
[[0 1 2]
 [0 1 2]]


# prove that array is storage efficient then list

In [96]:
import sys
import numpy as np
python_array = [1,2,3,4,5,6]
numpy_array = np.array([python_array])
print(sys.getsizeof(1)*len(python_array))
print(sys.getsizeof(1)*len(numpy_array))

168
28


In [115]:
import numpy as np
a = np.array([[[1,2],[3,4],[5,6]]])
print(a)
print(a.argmax())
print(a.argmin())
print(a.argsort())
print(a.sum(axis=0))
print(type(a))
print(a.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
5
0
[[[0 1]
  [0 1]
  [0 1]]]
[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
3


In [114]:
print(np.__version__)

1.23.5


# ADDITION

In [120]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[3,4,5]])
print(a1)
print(a2)
print(a1+a2)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [3 4 5]]
[[ 8 10 12]
 [ 7  9 11]]


# MULTIPLICATION

In [122]:
a1 = np.array([[1,2],[3,4],[5,6]])
a2 = np.array([[1,2],[3,4],[5,6]])
print(a1*a2)

[[ 1  4]
 [ 9 16]
 [25 36]]


# SQRT

In [127]:
s = np.array([4,16,49])
print(np.sqrt(s))

[2. 4. 7.]


# SUM

In [134]:
s = np.array([1,2,3,4,5])
print(s.sum())
print(np.sum(s))
print(np.max(s))
print(np.min(s))

15
15
5
1


# NON ZERO

In [138]:
n = np.array([[1,2,3],[4,5,6],[7,8,0]])
print(np.nonzero(n))

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))


# CONCATENATE

In [144]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.concatenate((a1,a2)))
print('\n')
print(np.concatenate((a1,a2),axis=0))

[1 2 3 4 5 6]


[1 2 3 4 5 6]


In [149]:
arr1 = np.array([[[1,2,3],[4,5,6]]])  
arr2 = np.array([[[7,8,9],[1,2,3]]])
print(np.concatenate((arr1,arr2),axis=0))
print('\r')
print(np.concatenate((arr1,arr2),axis=1))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 3]]]


# SLICING

In [152]:
s = np.array([2,4,6,8])
print(s[:])
print(s[:1])
print(s[1:])

[2 4 6 8]
[2]
[4 6 8]


In [163]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[:])
print(i[1:5])
print(i[1:5:2])
print(i[1:9:3])
print(i[::2])
print(i[::3])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[2 4]
[2 5 8]
[1 3 5 7 9]
[1 4 7]


# STACKING

In [170]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print(np.stack((a1,a2)))
print('\n')
print(np.hstack((a1,a2)))
print('\n')
print(np.vstack((a1,a2)))
print('\n')
print(np.dstack((a1,a2)))
print('\n')
print(np.stack((a1,a2),axis=1))
print('\n')
print(np.stack((a1,a2),axis=0))

[[1 2 3 4]
 [5 6 7 8]]


[1 2 3 4 5 6 7 8]


[[1 2 3 4]
 [5 6 7 8]]


[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


[[1 2 3 4]
 [5 6 7 8]]


# SPLITING

In [172]:
a = np.array([1,2,3,4,5])
print(np.array_split(a,2))

[array([1, 2, 3]), array([4, 5])]


In [182]:
a1 = np.array([1,2,3,4,5,6,7,8])
print(np.array_split(a1,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [185]:
a = np.array([1,2,3,4])
print(np.hsplit(a,2))

[array([1, 2]), array([3, 4])]
