### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [166]:
matrix = np.random.rand(5,5)
print(matrix)
print('\r')
matrix[[0,4]] = matrix[[4,0]]
print(matrix)

[[0.44649333 0.32086335 0.18685116 0.56710414 0.163158  ]
 [0.11690111 0.31192596 0.19025832 0.0304228  0.78435264]
 [0.89143812 0.56500405 0.58181388 0.64085745 0.7364315 ]
 [0.75123283 0.26706984 0.31155932 0.62404874 0.73682773]
 [0.936397   0.78519436 0.22767426 0.98547841 0.64447794]]

[[0.936397   0.78519436 0.22767426 0.98547841 0.64447794]
 [0.11690111 0.31192596 0.19025832 0.0304228  0.78435264]
 [0.89143812 0.56500405 0.58181388 0.64085745 0.7364315 ]
 [0.75123283 0.26706984 0.31155932 0.62404874 0.73682773]
 [0.44649333 0.32086335 0.18685116 0.56710414 0.163158  ]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [104]:
a = np.array([[1,2,3,4],[5,6,0,7]])
print(a)
print(a.nonzero())

[[1 2 3 4]
 [5 6 0 7]]
(array([0, 0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 0, 1, 3], dtype=int64))


In [124]:
a = np.array([[1,2,3,4],[5,6,0,7]])
f = a.flatten()
print(f)
l = []
for i in f:
    if i == 0:
        continue
    else:
        l.append(i)
print(l)
        

[1 2 3 4 5 6 0 7]
[1, 2, 3, 4, 5, 6, 7]


In [194]:
a = np.array([[1,2,3,4],[5,6,0,7]])
arr_no_zero = a[np.any(a!=0,axis=1)]
print(arr_no_zero)

[[1 2 3 4]
 [5 6 0 7]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [105]:
a = np.array([1.00000000+0.j,0.70710678+0.70710678j])
print(np.real(a))  
print(np.imag(a))

[1.         0.70710678]
[0.         0.70710678]


In [7]:
import numpy as np
a = np.array([1.00000000+0.j,0.70710678+0.70710678j])
real = [n.real for n in a]
imag = [n.imag for n in a]
print(np.array(real))
print(np.imag(imag))

[1.         0.70710678]
[0. 0.]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [106]:
a = np.array([10,10,20,20,30,30])
print(np.unique(a))

[10 20 30]


In [24]:
arr = np.array([10,10,20,20,30,30])
b = []
for i in range(len(arr)):
    for j in range(i+1,len(arr-1)):
        if arr[i]==arr[j]:
            b.append(arr[j])
print(b)
    
    

[10, 20, 30]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [10]:
r = np.random.rand(3,3,3)
r

array([[[0.57135525, 0.12411505, 0.47802143],
        [0.15697377, 0.57731153, 0.16296459],
        [0.19807375, 0.50146167, 0.1396342 ]],

       [[0.20079764, 0.14146342, 0.97268517],
        [0.94986233, 0.67020664, 0.87025478],
        [0.01563609, 0.59954208, 0.70995758]],

       [[0.96346382, 0.26871754, 0.56610592],
        [0.52871597, 0.26783473, 0.6043245 ],
        [0.42068949, 0.54704835, 0.03954263]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [152]:
a = np.random.random(10)
b = []
for i in a:
    if i>=i++:
        b.append(i)
b        

SyntaxError: invalid syntax (810862825.py, line 4)

### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [15]:
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print(np.array_equal(a,b))

False


In [17]:
a =np.array([1,2,3])
b = np.array([1,2,3])
print(np.array_equal(a,b))

True


In [157]:
a = np.array([1,2,3])
b = np.array([1,2,3])
   

### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [162]:
a =np.array([[10,40],[30,20]])
print(np.sort(a,axis=1))
print(a.flatten())

[[10 40]
 [20 30]]
[10 40 30 20]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [37]:
p = np.array([-1.6,-1.5,-0.3,0.1,1.4,1.8,2. ])
print(np.floor(p))
print(np.ceil(p))
print(np.trunc(p))

[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]
[-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [44]:
import calendar
yy = 2017
mm = 3
print(calendar.month(yy,mm))

     March 2017
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [184]:
from datetime import datetime, timedelta
start_time = datetime(2023,1,1,0,0,0)
datetime_object = [start_time+timedelta(hours=i) for i in range(24)]
datetime_array = np.array(datetime_object)
datetime_array

array([datetime.datetime(2023, 1, 1, 0, 0),
       datetime.datetime(2023, 1, 1, 1, 0),
       datetime.datetime(2023, 1, 1, 2, 0),
       datetime.datetime(2023, 1, 1, 3, 0),
       datetime.datetime(2023, 1, 1, 4, 0),
       datetime.datetime(2023, 1, 1, 5, 0),
       datetime.datetime(2023, 1, 1, 6, 0),
       datetime.datetime(2023, 1, 1, 7, 0),
       datetime.datetime(2023, 1, 1, 8, 0),
       datetime.datetime(2023, 1, 1, 9, 0),
       datetime.datetime(2023, 1, 1, 10, 0),
       datetime.datetime(2023, 1, 1, 11, 0),
       datetime.datetime(2023, 1, 1, 12, 0),
       datetime.datetime(2023, 1, 1, 13, 0),
       datetime.datetime(2023, 1, 1, 14, 0),
       datetime.datetime(2023, 1, 1, 15, 0),
       datetime.datetime(2023, 1, 1, 16, 0),
       datetime.datetime(2023, 1, 1, 17, 0),
       datetime.datetime(2023, 1, 1, 18, 0),
       datetime.datetime(2023, 1, 1, 19, 0),
       datetime.datetime(2023, 1, 1, 20, 0),
       datetime.datetime(2023, 1, 1, 21, 0),
       datetime.date

### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [95]:
a1 = np.array(['Python','PHP'])
a2 = np.array(['Java','C++'])
f = np.dstack((a1,a2))
print(f.flatten())

['Python' 'Java' 'PHP' 'C++']


In [ ]:
a1 = np.array(['Python','PHP'])
a2 = np.array(['Java','C++'])


In [26]:
import numpy as np

def addstring(s1, s2):
    a = []
    if len(s1) != len(s2):
        return False
    else:
        for i in range(len(s1)):
            re = s1[i] + s2[i]
            a.append(re)
    return a

s1 = np.array(['Python', 'PHP'], dtype='str')
s2 = np.array(['Java', 'C++'], dtype='str')
result = addstring(s1, s2)

print(result)


['PythonJava', 'PHPC++']
