# NUMPY TUTORIAL

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([1,2,3,45,66,7])
arr

array([ 1,  2,  3, 45, 66,  7])

In [3]:
arr = np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr = np.arange(1,15,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13])

# Create an array of all zeros

In [7]:
z = np.zeros((4,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Create an array of all ones

In [9]:
o = np.ones((4,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Create an array of constant

In [11]:
f = np.full((4,4),6)
f

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

# Create a 2x2 identity matrix

In [13]:
i = np.identity((2))
i

array([[1., 0.],
       [0., 1.]])

In [15]:
e = np.eye((2))
e

array([[1., 0.],
       [0., 1.]])

# Create an array filled with random values

In [16]:
r = np.random.random((3,3))
r

array([[0.11782548, 0.70669073, 0.62479834],
       [0.32992576, 0.56557328, 0.30229532],
       [0.09576566, 0.39888678, 0.6990151 ]])

# Array features

# Selecting array elements

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr[1]

array([4, 5, 6])

In [24]:
arr[1][2]

6

# Manipulating array shapes

# reshape() will change the shape of the array

In [30]:
d = np.arange(3,13).reshape(2,5)
d

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [31]:
d.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
d.ravel()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# The transpose() function is a linear algebraic function that transposes the

In [35]:
t = np.arange(4,13).reshape(3,3)
print(t)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
t.transpose()

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [38]:
np.resize(1,9)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

# The stacking of NumPy arrays

In [39]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr = arr1.reshape((3,3))

In [50]:
arr2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [52]:
s = np.hstack((arr,arr2))
s

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

# if we dont use axis 1 then it vertical stake

In [55]:
c = np.concatenate((arr,arr2),axis=1)
c

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [56]:
s = np.concatenate((arr,arr2))
s

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# Vertical stacking

In [62]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr4 = np.array([[11,12,13],[14,15,16],[17,18,19]])
arr4

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [64]:
v = np.vstack((arr3,arr4))
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# Depth stacking

In [65]:
a = np.dstack((arr3,arr4))
a

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]],

       [[ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

# Stack

In [68]:
s = np.stack((arr3,arr4))
s

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

# Column stacking

In [69]:
a1 = np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [70]:
a2 = np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [72]:
c = np.column_stack((a1,a2))
c

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# Row stacking

In [73]:
r = np.row_stack((a1,a2))
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
#Partitioning NumPy arrays

In [79]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [80]:
from numpy import *
print(sum(range(5),-1))

10
